name: Bandit Scan (python code)

on:
  pull_request:
    branches: ["main","dev"]
    paths: 
      - '**.py'

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: Bandit results
          comment-author: github-actions
        continue-on-error: true
      - name: Delete comment
        uses: detomarco/delete-comments@v1.0.4
        if: steps.fc.outcome == 'success'
        with: 
          comment-id: ${{ steps.fc.outputs.comment-id }}
      - name: Run bandit
        if: '!cancelled()'
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
      - name: Run bandit again (to upload)
        if: '!cancelled()'
        run: |
          pip install bandit
          bandit . -r -o CI_bandit_report.html -f html
        continue-on-error: true
      - name: Upload artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: Bandit vuln report
          path: |
            CI_bandit_report.html
          
