name: build-current-version
on:
  push:
    branches:
      - weiming-github-workflow

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  build-and-scout:
    runs-on:
      labels: large_16c
    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get version
      id: version
      uses: SebRollen/toml-action@v1.2.0
      with:
        file: pyproject.toml  
        field: tool.poetry.version

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        secrets: |
          GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
        tags: ghcr.io/cap-dcwiz/dctwin:${{ steps.version.outputs.value }}

    - name: Authenticate to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: quickview,cves,recommendations
        image: ghcr.io/cap-dcwiz/dctwin:${{ steps.version.outputs.value }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

