name: Security Scanning

on:
  pull_request:
    branches: ["main","dev"]
  schedule:
    - cron: '42 13 * * 4'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
  safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup safety
        run: |
          pip install safety
      - name: Run safety
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        id: run_safety
        run: |
          set +e
          out=$(safety --stage cicd scan --detailed-output)
          err=$?
          echo -- "$out"
          {
            echo 'SAFETY<<Eof'
            echo "$out"
            echo 'Eof'
          } >> "$GITHUB_OUTPUT"
          echo -- "$out" > CI_safety_report.txt
          exit $?
      - name: Comment with safety results
        uses: mshick/add-pr-comment@v2.8.2
        if: '!cancelled()'
        with:
          message: ${{ steps.run_safety.outputs.SAFETY }}
          message-id: 15
          update-only: true
      - name: Upload artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: Safety vuln report
          path: CI_safety_report.txt
          
